name: super_image
description: A Smart widget that renders images on screen.
version: 0.0.6
publish_to: none
homepage: https://github.com/RagehAz/super_image.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bldrs_theme:
    git:
      url: https://github.com/RagehAz/bldrs_theme.git
  widget_fader:
    git:
      url: https://github.com/RagehAz/widget_fader.git
  image: ^3.2.2
  websafe_svg: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0+1

flutter:
